- hosts: all
  tasks:
    - name: delete old deployment
      command: minikube kubectl -- delete -f /home/ubuntu/Deployment.yml
      ignore_errors: yes #This is just here so that if nothing is here to be deleted, the error will be neglected
      
    - name: delete old service
      command: minikube kubectl -- delete -f /home/ubuntu/Service.yml
      ignore_errors: yes
      
    - name: create new deployment
      command: minikube kubectl -- apply -f /home/ubuntu/Deployment.yml
      
    - name: create new service
      command: minikube kubectl -- apply -f /home/ubuntu/Service.yml