kind: Service
apiVersion: v1
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30007    # Fixed port between 30000-32767
  selector:
    app: mrdevops
  type: NodePort        # Changed from LoadBalancer to NodePort